# Generated by Django 5.2.11 on 2026-03-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PBMClaim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('claim_id', models.CharField(max_length=32)),
                ('transaction_id', models.CharField(max_length=64)),
                ('claim_status', models.CharField(max_length=32)),
                ('patient_id', models.CharField(max_length=32)),
                ('age_group', models.CharField(max_length=16)),
                ('region', models.CharField(max_length=64)),
                ('plan_id', models.CharField(max_length=32)),
                ('group_id', models.CharField(max_length=32)),
                ('drug_name', models.CharField(max_length=128)),
                ('ndc_code', models.CharField(max_length=32)),
                ('therapeutic_class', models.CharField(max_length=64)),
                ('specialty_drug_flag', models.IntegerField()),
                ('diagnosis_code', models.CharField(max_length=32)),
                ('disease_category', models.CharField(max_length=64)),
                ('ingredient_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dispensing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('copay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rebate_estimate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('days_supply', models.IntegerField()),
                ('refill_number', models.IntegerField()),
                ('pharmacy_id', models.CharField(max_length=32)),
                ('pharmacy_type', models.CharField(max_length=64)),
                ('prescriber_id', models.CharField(max_length=32)),
                ('fill_date', models.CharField(max_length=16)),
                ('adjudication_time', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'PBM Claim',
                'verbose_name_plural': 'PBM Claims',
                'db_table': 'pbm_claims',
                'ordering': ['-fill_date', 'claim_id'],
                'managed': False,
            },
        ),
    ]
